#!/bin/bash
printf "%0.2f\n" $NUM 100) printf '%x\n' $DECIMAL 101) tr '[A-Za-z]' '[N-ZA-Mn-za-m]' 102) paste - - | cut -f 1 103) printf "%o\n" $((5#$(echo $WATER | tr 'water' '01234') + 5#$(echo $STIR | tr 'stir.' '01234'))) | tr '01234567' 'bestchol'
